<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPmWC2JP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPmWC2JP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPmWC2JP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPmWC2JP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPmWC2JP\App_KernelDevDebugContainer([
    'container.build_hash' => 'PmWC2JP',
    'container.build_id' => 'd313bc33',
    'container.build_time' => 1607372906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPmWC2JP');
