<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmPjPl0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmPjPl0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmPjPl0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmPjPl0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUmPjPl0\App_KernelDevDebugContainer([
    'container.build_hash' => 'UmPjPl0',
    'container.build_id' => '64f9842d',
    'container.build_time' => 1607274737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmPjPl0');
